name: gateway
kind: Deployment
replicaCount: 1

image:
  repository: gateway
  tag: "0.0.1-SNAPSHOT"
  pullPolicy: Never

containerPort: 8000

service:
  enabled: true
  type: ClusterIP
  port: 8000

env:
  - name: SPRING_PROFILES_ACTIVE
    value: kubernetes
  - name: SPRING_CLOUD_NACOS_HOST
    value: nacos-cs
  - name: SPRING_CLOUD_ROCKETMQ_PROXY_HOST
    value: rocketmq-proxy
  - name: OTEL_SERVICE_NAME
    value: gateway
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector-opentelemetry-collector:4318
  - name: OTEL_LOGS_EXPORTER
    value: otlp
  - name: OTEL_TRACES_EXPORTER
    value: otlp
  - name: OTEL_METRICS_EXPORTER
    value: otlp
  - name: OTEL_CONFIG_FILE
    value: ""

  - name: JVM_OPTS
    value: "-XX:MaxRAMPercentage=75.0"

livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 40

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 60

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
