userconfig:
  service:
    extensions: [jaeger_storage, jaeger_query, healthcheckv2]
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [jaeger_storage_exporter]
  extensions:
    healthcheckv2:
      use_v2: true
      http:
        endpoint: 0.0.0.0:13133
    jaeger_storage:
      backends:
        primary_store:
          memory: {}
    jaeger_query:
      base_path: /jaeger
      storage:
        traces: primary_store
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  exporters:
    jaeger_storage_exporter:
      trace_storage: primary_store

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

fullnameOverride: jaeger-all-in-one

allInOne:
  enabled: true
  image:
    repository: jaegertracing/all-in-one
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

storage:
  type: memory

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false

spark:
  enabled: false