config: |
  stream_over_http_enabled: true
  memberlist:
    join_members:
      - tempo
  multitenancy_enabled: false
  usage_report:
    reporting_enabled: false
  server:
    http_listen_port: 3200
    log_level: info
  distributor:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    ring:
      kvstore:
        store: memberlist
  ingester:
    max_block_duration: 5m
    lifecycler:
      ring:
        kvstore:
          store: memberlist
      heartbeat_period: 1s
      num_tokens: 512
      min_ready_duration: 0s
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
  metrics_generator:
    ring:
      kvstore:
        store: memberlist
    storage:
      path: /var/tempo/generator
    processor:
      service_graphs:
        histogram_buckets: [0.1, 0.5, 1, 2, 5, 10]
      span_metrics:
        histogram_buckets: [0.1, 0.5, 1, 2, 5, 10]
      local_blocks:
        filter_server_spans: false
    registry:
      external_labels:
        source: tempo
  query_frontend:
    search:
      target_bytes_per_job: 104857600
      max_result_limit: 10000
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
    metrics:
      concurrent_jobs: 8
      target_bytes_per_job: 104857600
    trace_by_id:
      query_shards: 2
      duration_slo: 5s
  querier:
    max_concurrent_queries: 20

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
