repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana-community.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
helmDefaults:
  createNamespace: true
  wait: false

releases:
  # Middleware
  - name: mysql
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/mysql.yaml

  - name: nacos
    namespace: microservices
    chart: ./external/nacos-k8s/helm
    values:
      - values/nacos.yaml
    needs:
      - mysql

  - name: rocketmq
    namespace: microservices
    chart: oci://registry-1.docker.io/apache/rocketmq
    version: "0.0.1"
    values:
      - values/rocketmq.yaml
    needs:
      - nacos

  - name: rocketmq-init-topics
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/rocketmq-init-topics.yaml
    needs:
      - rocketmq

  # Observability
  - name: eck-operator
    namespace: microservices
    chart: elastic/eck-operator
    labels:
      stack: observability
    values:
      - values/eck-operator.yaml

  - name: eck-stack
    namespace: microservices
    chart: elastic/eck-stack
    labels:
      stack: observability
    values:
      - values/eck-stack.yaml
    needs:
      - eck-operator

  - name: kube-prometheus-stack
    namespace: microservices
    chart: prometheus-community/kube-prometheus-stack
    version: "83.4.0"
    labels:
      stack: observability
    values:
      - values/kube-prometheus-stack.yaml

  - name: grafana-dashboards
    chart: ./charts/grafana-dashboards-configmap
    namespace: microservices
    labels:
      stack: observability
    needs:
      - kube-prometheus-stack

  - name: loki
    namespace: microservices
    chart: grafana/loki
    version: "9.2.0"
    labels:
      stack: observability
    values:
      - values/loki.yaml

  - name: tempo
    namespace: microservices
    chart: grafana/tempo
    version: "2.0.0"
    labels:
      stack: observability
    values:
      - values/tempo.yaml

  - name: jaeger
    namespace: microservices
    chart: jaegertracing/jaeger
    version: "4.6.0"
    labels:
      stack: observability
    values:
      - values/jaeger.yaml

  - name: zipkin
    namespace: microservices
    chart: ./charts/microservice
    labels:
      stack: observability
    values:
      - values/zipkin.yaml

  - name: otel-collector
    namespace: microservices
    chart: open-telemetry/opentelemetry-collector
    version: "0.150.0"
    values:
      - values/otel-collector.yaml
    needs:
      - jaeger
      - zipkin
      - eck-stack
      - kube-prometheus-stack
      - loki
      - tempo

  - name: sentinel-dashboard
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/sentinel-dashboard.yaml

  # App Services
  - name: gateway
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/gateway.yaml
    needs:
      - rocketmq
      - nacos
      - otel-collector

  - name: multiplication
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/multiplication.yaml
    needs:
      - rocketmq
      - nacos
      - otel-collector

  - name: gamification
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/gamification.yaml
    needs:
      - rocketmq
      - nacos
      - otel-collector

  - name: logs
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/logs.yaml
    needs:
      - rocketmq
      - nacos
      - otel-collector

  - name: frontend
    namespace: microservices
    chart: ./charts/microservice
    values:
      - values/frontend.yaml

  # Ingress
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    values:
      - values/ingress-nginx.yaml

  - name: ingress-rules
    chart: ./charts/ingress-rules
    namespace: microservices
    values:
      - values/ingress-rules.yaml
    needs:
      - ingress-nginx/ingress-nginx
