spring.application.name=multiplication
spring.jpa.open-in-view=false
# For educational purposes we will show the SQL in console
# spring.jpa.show-sql=true
rocketmq.attempts=attempts-topic

#multiplication app as a producer
rocketmq.producer.endpoints=${SPRING_CLOUD_ROCKETMQ_PROXY_HOST:localhost}:8081
rocketmq.producer.request-timeout=10

##working with default logback configuration for distributed tracing
logging.pattern.level=[${spring.application.name:-},%X{traceId:-},%X{spanId:-}]
logging.include-application-name=false
#---
spring.config.activate.on-profile=local
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:~/multiplication;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
#---
spring.config.activate.on-profile=test
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:mem:multiplication;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=create-drop
#---
spring.config.activate.on-profile=docker
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:file:~/multiplication;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
#---
spring.config.activate.on-cloud-platform=kubernetes
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:file:~/multiplication;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
