spring.application.name=gamification
spring.jpa.open-in-view=false
# For educational purposes we will show the SQL in console
# spring.jpa.show-sql=true

#config both on the producer and consumer as we donot know which one will start first
rocketmq.attempts=attempts-topic

#spring.config.import=optional:consul:
spring.cloud.compatibility-verifier.enabled=false

#multiplication app as a producer
#rocketmq.simple-consumer.endpoints=${SPRING_CLOUD_ROCKETMQ_PROXY_HOST:localhost}:8081
#rocketmq.simple-consumer.filter-expression-type=tag
#rocketmq.simple-consumer.tag=*

rocketmq.push-consumer.endpoints=${SPRING_CLOUD_ROCKETMQ_PROXY_HOST:localhost}:8081
rocketmq.push-consumer.tag=*
#rocketmq.push-consumer.access-key=
#rocketmq.push-consumer.secret-key=

##working with default logback configuration for distributed tracing
logging.pattern.level=[${spring.application.name:-},%X{traceId:-},%X{spanId:-}]
logging.include-application-name=false
#---
spring.config.activate.on-profile=local
# Gives us access to the H2 database web console
spring.h2.console.enabled=true
# Creates the database in a file
spring.datasource.url=jdbc:h2:file:~/gamification;AUTO_SERVER=TRUE
# Creates or updates the schema if needed
spring.jpa.hibernate.ddl-auto=update
#---
spring.config.activate.on-profile=test
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:mem:gamification;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=create-drop
#---
spring.config.activate.on-profile=docker
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:file:~/gamification;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
#---
spring.config.activate.on-cloud-platform=kubernetes
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:file:~/gamification;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update


